version: '3.8'
services:
  nginx:   
    build:
      context: ./docker/nginx 
    container_name: nginx-container  
    ports:   
      - 80:80
    volumes:
      - ./app:/var/www/symfony
  php-fpm:
    build: 
      context: ./docker/app
    container_name: php-fpm
    ports:
      - 9000:9000
    volumes:
      - ./app:/var/www/symfony
    