version: '3.8'
services:
  nginx:   
    build:
      context: ./nginx 
    container_name: nginx-container  
    ports:   
      - 80:80
    volumes:
      - ../app:/var/www/symfony
    networks:
      - symfosite_app

  php-fpm:
    build: 
      context: ./app
    container_name: php-fpm
    ports:
      - 9000:9000
    volumes:
      - ../app:/var/www/symfony
    networks:
      - symfosite_app

  mysql:
    image: mysql
    container_name: mysql-db
    ports:
      - 3306:3306
    platform: linux/x86_64
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - "../db-app:/var/lib/mysql"
    networks:
      - symfosite_app
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

networks:
    symfosite_app:
    